// Copyright (c) 2022 Yaohui Wang (yaohuiwang@outlook.com)
// FlexLB is licensed under Mulan PubL v2.
// You can use this software according to the terms and conditions of the Mulan PubL v2.
// You may obtain a copy of Mulan PubL v2 at:
//         http://license.coscl.org.cn/MulanPubL-2.0
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See the Mulan PubL v2 for more details.

// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"gitee.com/flexlb/flexlb-client-go/models"
)

// NewModifyParams creates a new ModifyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewModifyParams() *ModifyParams {
	return &ModifyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewModifyParamsWithTimeout creates a new ModifyParams object
// with the ability to set a timeout on a request.
func NewModifyParamsWithTimeout(timeout time.Duration) *ModifyParams {
	return &ModifyParams{
		timeout: timeout,
	}
}

// NewModifyParamsWithContext creates a new ModifyParams object
// with the ability to set a context for a request.
func NewModifyParamsWithContext(ctx context.Context) *ModifyParams {
	return &ModifyParams{
		Context: ctx,
	}
}

// NewModifyParamsWithHTTPClient creates a new ModifyParams object
// with the ability to set a custom HTTPClient for a request.
func NewModifyParamsWithHTTPClient(client *http.Client) *ModifyParams {
	return &ModifyParams{
		HTTPClient: client,
	}
}

/* ModifyParams contains all the parameters to send to the API endpoint
   for the modify operation.

   Typically these are written to a http.Request.
*/
type ModifyParams struct {

	/* Config.

	   Instance request
	*/
	Config *models.InstanceConfig

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyParams) WithDefaults() *ModifyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the modify params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ModifyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the modify params
func (o *ModifyParams) WithTimeout(timeout time.Duration) *ModifyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the modify params
func (o *ModifyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the modify params
func (o *ModifyParams) WithContext(ctx context.Context) *ModifyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the modify params
func (o *ModifyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the modify params
func (o *ModifyParams) WithHTTPClient(client *http.Client) *ModifyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the modify params
func (o *ModifyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConfig adds the config to the modify params
func (o *ModifyParams) WithConfig(config *models.InstanceConfig) *ModifyParams {
	o.SetConfig(config)
	return o
}

// SetConfig adds the config to the modify params
func (o *ModifyParams) SetConfig(config *models.InstanceConfig) {
	o.Config = config
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Config != nil {
		if err := r.SetBodyParam(o.Config); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
