// Copyright (c) 2022 Yaohui Wang (yaohuiwang@outlook.com)
// FlexLB is licensed under Mulan PubL v2.
// You can use this software according to the terms and conditions of the Mulan PubL v2.
// You may obtain a copy of Mulan PubL v2 at:
//         http://license.coscl.org.cn/MulanPubL-2.0
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
// See the Mulan PubL v2 for more details.

// Code generated by go-swagger; DO NOT EDIT.

package instance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewStopParams creates a new StopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewStopParams() *StopParams {
	return &StopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewStopParamsWithTimeout creates a new StopParams object
// with the ability to set a timeout on a request.
func NewStopParamsWithTimeout(timeout time.Duration) *StopParams {
	return &StopParams{
		timeout: timeout,
	}
}

// NewStopParamsWithContext creates a new StopParams object
// with the ability to set a context for a request.
func NewStopParamsWithContext(ctx context.Context) *StopParams {
	return &StopParams{
		Context: ctx,
	}
}

// NewStopParamsWithHTTPClient creates a new StopParams object
// with the ability to set a custom HTTPClient for a request.
func NewStopParamsWithHTTPClient(client *http.Client) *StopParams {
	return &StopParams{
		HTTPClient: client,
	}
}

/* StopParams contains all the parameters to send to the API endpoint
   for the stop operation.

   Typically these are written to a http.Request.
*/
type StopParams struct {

	/* Name.

	   Instance name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopParams) WithDefaults() *StopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *StopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the stop params
func (o *StopParams) WithTimeout(timeout time.Duration) *StopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stop params
func (o *StopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stop params
func (o *StopParams) WithContext(ctx context.Context) *StopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stop params
func (o *StopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the stop params
func (o *StopParams) WithHTTPClient(client *http.Client) *StopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the stop params
func (o *StopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the stop params
func (o *StopParams) WithName(name string) *StopParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the stop params
func (o *StopParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *StopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
